---

- name: Include variables
  vars: 
  include_vars:
    file: vars/main.yml

- name: Install matrix server
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - lsof
    - curl
    - python
    - makepasswd
    - sqlite3
    - python-pip
    - matrix-synapse
  register: aptout

